let num1 = Number(prompt("Digite um número: "))
let num2 = Number(prompt("Digite outro número: "))
console.log(`O primeiro numero ${num1} é maior que o segundo ${num2}? ${num1>num2}`)
console.log(`O primeiro numero ${num1} é igual ao segundo ${num2}? ${num1 == num2}`)
console.log(`O primeiro numero ${num1} é divisível pelo segundo ${num2}? ${num1 % num2 == 0}`)
console.log(`O segundo numero ${num2} é divisível pelo primeiro ${num1}? ${num2 % num1 == 0}`)